-- Copy YOUR Real Registration Data to Institution Profiles
-- This script copies your actual registration data from institutions table to institution_profiles

-- 1. First, let's see what's in the institutions table
SELECT 
    'Your Real Registration Data in Institutions Table' as check_type,
    id,
    name,
    type,
    establishment_year,
    registration_number,
    pan,
    gst,
    official_email,
    primary_contact,
    secondary_contact,
    website,
    complete_address,
    city,
    state,
    pincode,
    landmark,
    latitude,
    longitude,
    owner_name,
    owner_contact,
    status,
    agree_terms,
    agree_background_verification,
    primary_contact_verified,
    owner_contact_verified,
    created_at,
    updated_at
FROM institutions 
WHERE official_email = 'maseerah2003@gmail.com'
ORDER BY created_at DESC;

-- 2. Update institution_profiles with YOUR real data from institutions table
UPDATE institution_profiles 
SET 
    institution_name = (SELECT name FROM institutions WHERE official_email = 'maseerah2003@gmail.com' ORDER BY created_at DESC LIMIT 1),
    institution_type = (SELECT type FROM institutions WHERE official_email = 'maseerah2003@gmail.com' ORDER BY created_at DESC LIMIT 1),
    established_year = (SELECT establishment_year FROM institutions WHERE official_email = 'maseerah2003@gmail.com' ORDER BY created_at DESC LIMIT 1),
    registration_number = (SELECT registration_number FROM institutions WHERE official_email = 'maseerah2003@gmail.com' ORDER BY created_at DESC LIMIT 1),
    pan_number = (SELECT pan FROM institutions WHERE official_email = 'maseerah2003@gmail.com' ORDER BY created_at DESC LIMIT 1),
    gst_number = (SELECT gst FROM institutions WHERE official_email = 'maseerah2003@gmail.com' ORDER BY created_at DESC LIMIT 1),
    official_email = (SELECT official_email FROM institutions WHERE official_email = 'maseerah2003@gmail.com' ORDER BY created_at DESC LIMIT 1),
    primary_contact_number = (SELECT primary_contact FROM institutions WHERE official_email = 'maseerah2003@gmail.com' ORDER BY created_at DESC LIMIT 1),
    secondary_contact_number = (SELECT secondary_contact FROM institutions WHERE official_email = 'maseerah2003@gmail.com' ORDER BY created_at DESC LIMIT 1),
    website_url = (SELECT website FROM institutions WHERE official_email = 'maseerah2003@gmail.com' ORDER BY created_at DESC LIMIT 1),
    address = (SELECT complete_address FROM institutions WHERE official_email = 'maseerah2003@gmail.com' ORDER BY created_at DESC LIMIT 1),
    city = (SELECT city FROM institutions WHERE official_email = 'maseerah2003@gmail.com' ORDER BY created_at DESC LIMIT 1),
    state = (SELECT state FROM institutions WHERE official_email = 'maseerah2003@gmail.com' ORDER BY created_at DESC LIMIT 1),
    pin_code = (SELECT pincode FROM institutions WHERE official_email = 'maseerah2003@gmail.com' ORDER BY created_at DESC LIMIT 1),
    landmark = (SELECT landmark FROM institutions WHERE official_email = 'maseerah2003@gmail.com' ORDER BY created_at DESC LIMIT 1),
    google_maps_location = CASE 
        WHEN (SELECT latitude FROM institutions WHERE official_email = 'maseerah2003@gmail.com' ORDER BY created_at DESC LIMIT 1) IS NOT NULL 
        AND (SELECT longitude FROM institutions WHERE official_email = 'maseerah2003@gmail.com' ORDER BY created_at DESC LIMIT 1) IS NOT NULL
        THEN json_build_object(
            'lat', (SELECT latitude FROM institutions WHERE official_email = 'maseerah2003@gmail.com' ORDER BY created_at DESC LIMIT 1),
            'lng', (SELECT longitude FROM institutions WHERE official_email = 'maseerah2003@gmail.com' ORDER BY created_at DESC LIMIT 1)
        )::text
        ELSE NULL
    END,
    owner_name = (SELECT owner_name FROM institutions WHERE official_email = 'maseerah2003@gmail.com' ORDER BY created_at DESC LIMIT 1),
    owner_contact_number = (SELECT owner_contact FROM institutions WHERE official_email = 'maseerah2003@gmail.com' ORDER BY created_at DESC LIMIT 1),
    agree_to_terms = (SELECT agree_terms FROM institutions WHERE official_email = 'maseerah2003@gmail.com' ORDER BY created_at DESC LIMIT 1),
    agree_to_background_verification = (SELECT agree_background_verification FROM institutions WHERE official_email = 'maseerah2003@gmail.com' ORDER BY created_at DESC LIMIT 1),
    verified = (SELECT primary_contact_verified FROM institutions WHERE official_email = 'maseerah2003@gmail.com' ORDER BY created_at DESC LIMIT 1),
    updated_at = NOW()
WHERE user_id = '6b0f0c18-08fe-431b-af56-c4ab23e3b25c';

-- 3. Verify the update with YOUR real data
SELECT 
    'Updated Institution Profile with YOUR Real Data' as check_type,
    id,
    institution_name,
    institution_type,
    established_year,
    registration_number,
    pan_number,
    gst_number,
    official_email,
    primary_contact_number,
    secondary_contact_number,
    website_url,
    address,
    city,
    state,
    pin_code,
    landmark,
    owner_name,
    owner_contact_number,
    agree_to_terms,
    agree_to_background_verification,
    verified,
    created_at,
    updated_at
FROM institution_profiles 
WHERE user_id = '6b0f0c18-08fe-431b-af56-c4ab23e3b25c';

-- 4. Check if there are any other fields that need to be populated
SELECT 
    'Remaining Empty Fields' as check_type,
    id,
    institution_name,
    course_categories,
    course_details,
    class_timings,
    total_classrooms,
    classroom_capacity,
    library_available,
    computer_lab_available,
    wifi_available,
    parking_available,
    cafeteria_available,
    air_conditioning_available,
    cctv_security_available,
    wheelchair_accessible,
    projectors_smart_boards,
    audio_system,
    physics_lab,
    chemistry_lab,
    biology_lab,
    computer_lab,
    language_lab,
    indoor_games,
    outdoor_playground,
    gymnasium,
    swimming_pool,
    transportation_provided,
    hostel_facility,
    study_material_provided,
    online_classes,
    recorded_sessions,
    mock_tests_assessments,
    career_counseling,
    job_placement_assistance,
    total_current_students,
    average_batch_size,
    student_teacher_ratio,
    admission_test_required,
    minimum_qualification,
    age_restrictions,
    admission_fees,
    security_deposit,
    refund_policy,
    total_teaching_staff,
    total_non_teaching_staff,
    average_faculty_experience,
    principal_director_name,
    principal_director_qualification,
    principal_director_experience,
    principal_director_photo,
    principal_director_bio,
    department_heads,
    phd_holders,
    post_graduates,
    graduates,
    professional_certified,
    awards_received,
    publications,
    industry_experience,
    training_programs,
    board_exam_results,
    competitive_exam_results,
    institution_awards,
    student_achievements,
    accreditations,
    success_stories,
    courses,
    payment_modes,
    emi_available,
    payment_schedule,
    late_payment_penalty,
    scholarship_available,
    scholarship_criteria,
    discount_multiple_courses,
    sibling_discount,
    early_bird_discount,
    education_loan_assistance,
    installment_facility,
    hardship_support,
    primary_contact_person,
    contact_designation,
    contact_phone_number,
    contact_email_address,
    whatsapp_number,
    best_time_to_contact,
    facebook_page_url,
    instagram_account_url,
    youtube_channel_url,
    linkedin_profile_url,
    google_my_business_url,
    emergency_contact_person,
    local_police_station_contact,
    nearest_hospital_contact,
    fire_department_contact,
    business_registration_certificate,
    education_board_affiliation_certificate,
    fire_safety_certificate,
    building_plan_approval,
    pan_card_document,
    gst_certificate_document,
    bank_account_details_document,
    institution_photographs,
    insurance_documents,
    accreditation_certificates,
    award_certificates,
    faculty_qualification_certificates,
    safety_compliance_certificates
FROM institution_profiles 
WHERE user_id = '6b0f0c18-08fe-431b-af56-c4ab23e3b25c';
