-- Update Institution Profile with 7-Step Registration Data (FINAL FIXED)
-- This script updates the institution profile with comprehensive 7-step registration data

-- 1. First, let's see what we currently have
SELECT 
    'Current State' as check_type,
    id,
    institution_name,
    institution_type,
    established_year,
    registration_number,
    pan_number,
    gst_number,
    official_email,
    primary_contact_number,
    secondary_contact_number,
    website_url,
    address,
    city,
    state,
    pin_code,
    landmark,
    owner_name,
    owner_contact_number,
    course_categories,
    course_details,
    class_timings,
    created_at
FROM institution_profiles 
WHERE user_id = '6b0f0c18-08fe-431b-af56-c4ab23e3b25c';

-- 2. Update the institution profile with comprehensive 7-step registration data
UPDATE institution_profiles 
SET 
    -- Basic Information (Step 1)
    institution_name = 'Bright Future Institute of Technology',
    institution_type = 'Educational Institution',
    established_year = 2020,
    registration_number = 'BFIT-2020-001',
    pan_number = 'ABCDE1234F',
    gst_number = '22ABCDE1234F1Z5',
    official_email = 'maseerah2003@gmail.com',
    primary_contact_number = '+91-9876543210',
    secondary_contact_number = '+91-9876543211',
    website_url = 'https://brightfuturetech.edu',
    
    -- Address Information (Step 2)
    address = '123 Education Street, Tech City, Near Tech Park',
    city = 'Mumbai',
    state = 'Maharashtra',
    pin_code = '400001',
    landmark = 'Near Tech Park',
    google_maps_location = '{"lat": 19.0760, "lng": 72.8777}',
    
    -- Owner Information (Step 3)
    owner_name = 'Dr. Anil Kumar',
    owner_contact_number = '+91-9876543212',
    
    -- Legal Documents (Step 4)
    business_license = 'BL-2020-001',
    registration_certificate = 'RC-2020-001',
    agree_to_terms = true,
    agree_to_background_verification = true,
    
    -- Infrastructure (Step 5)
    total_classrooms = 25,
    classroom_capacity = 30,
    library_available = true,
    computer_lab_available = true,
    wifi_available = true,
    parking_available = true,
    cafeteria_available = true,
    air_conditioning_available = true,
    cctv_security_available = true,
    wheelchair_accessible = true,
    projectors_smart_boards = true,
    audio_system = true,
    physics_lab = true,
    chemistry_lab = true,
    biology_lab = true,
    computer_lab = true,
    language_lab = true,
    indoor_games = true,
    outdoor_playground = true,
    gymnasium = true,
    swimming_pool = false,
    transportation_provided = true,
    hostel_facility = true,
    study_material_provided = true,
    online_classes = true,
    recorded_sessions = true,
    mock_tests_assessments = true,
    career_counseling = true,
    job_placement_assistance = true,
    
    -- Photos (Step 6) - ALL JSONB
    main_building_photo = 'https://example.com/main-building.jpg',
    classroom_photos = '["https://example.com/classroom1.jpg", "https://example.com/classroom2.jpg"]'::jsonb,
    laboratory_photos = '["https://example.com/lab1.jpg", "https://example.com/lab2.jpg"]'::jsonb,
    facilities_photos = '["https://example.com/facility1.jpg", "https://example.com/facility2.jpg"]'::jsonb,
    achievement_photos = '["https://example.com/achievement1.jpg", "https://example.com/achievement2.jpg"]'::jsonb,
    
    -- Course Information (Step 7) - ALL JSONB
    course_categories = '{"engineering": ["Computer Science", "Electronics", "Mechanical"], "management": ["MBA", "BBA"], "science": ["Physics", "Chemistry", "Mathematics"]}'::jsonb,
    course_details = '{"Computer Science": {"duration": "4 years", "fees": 50000, "seats": 60}, "MBA": {"duration": "2 years", "fees": 75000, "seats": 40}}'::jsonb,
    total_current_students = 500,
    average_batch_size = 30,
    student_teacher_ratio = '15:1',
    class_timings = '{"morning": "8:00 AM - 12:00 PM", "afternoon": "1:00 PM - 5:00 PM", "evening": "6:00 PM - 10:00 PM"}'::jsonb,
    admission_test_required = true,
    minimum_qualification = '12th Grade',
    age_restrictions = '16-25 years',
    admission_fees = 5000,
    security_deposit = 10000,
    refund_policy = '50% refund if withdrawn within 30 days',
    
    -- Faculty Information
    total_teaching_staff = 25,
    total_non_teaching_staff = 15,
    average_faculty_experience = '5-10 years',
    principal_director_name = 'Dr. Anil Kumar',
    principal_director_qualification = 'Ph.D. in Computer Science',
    principal_director_experience = 15,
    principal_director_photo = 'https://example.com/principal.jpg',
    principal_director_bio = 'Experienced educator with 15 years in the field',
    department_heads = '{"Computer Science": "Dr. Rajesh Kumar", "Electronics": "Dr. Priya Sharma", "Mechanical": "Dr. Amit Singh"}'::jsonb,
    phd_holders = 10,
    post_graduates = 15,
    graduates = 5,
    professional_certified = 8,
    awards_received = 'Best Engineering College 2020, Excellence in Education 2021',
    publications = '50+ research papers published in international journals',
    industry_experience = 'Faculty members have 5-15 years industry experience',
    training_programs = 'Regular workshops and seminars conducted',
    
    -- Academic Performance - ALL JSONB
    board_exam_results = '{"2020": {"pass_percentage": 95, "distinction": 60}, "2021": {"pass_percentage": 97, "distinction": 65}}'::jsonb,
    competitive_exam_results = '{"JEE": {"qualified": 80, "top_1000": 15}, "GATE": {"qualified": 70, "top_100": 5}}'::jsonb,
    institution_awards = '["Best Engineering College 2020", "Excellence in Education 2021", "Innovation Award 2022"]'::jsonb,
    student_achievements = '["National Science Olympiad Winner", "Hackathon Champions", "Research Paper Publications"]'::jsonb,
    accreditations = '["NAAC A+ Grade", "NBA Accredited", "ISO 9001:2015 Certified"]'::jsonb,
    success_stories = '["95% placement rate", "Average package 8 LPA", "Top companies: TCS, Infosys, Wipro"]'::jsonb,
    
    -- Payment Information - ALL JSONB
    courses = '["Computer Science Engineering", "Electronics Engineering", "Mechanical Engineering", "MBA", "BBA"]'::jsonb,
    payment_modes = '["Cash", "Cheque", "Online Transfer", "Credit Card", "Debit Card"]'::jsonb,
    emi_available = 'Yes, 6-12 months EMI available',
    payment_schedule = 'Semester-wise payment',
    late_payment_penalty = '2% per month',
    scholarship_available = 'Merit-based and need-based scholarships',
    scholarship_criteria = 'Academic performance and financial need',
    discount_multiple_courses = '10% discount for multiple courses',
    sibling_discount = '5% discount for siblings',
    early_bird_discount = '15% discount for early admission',
    education_loan_assistance = 'Assistance provided for education loans',
    installment_facility = 'Monthly installments available',
    hardship_support = 'Special consideration for financially challenged students',
    
    -- Contact Information
    primary_contact_person = 'Dr. Anil Kumar',
    contact_designation = 'Principal',
    contact_phone_number = '+91-9876543210',
    contact_email_address = 'maseerah2003@gmail.com',
    whatsapp_number = '+91-9876543210',
    best_time_to_contact = '9:00 AM - 6:00 PM',
    facebook_page_url = 'https://facebook.com/brightfuturetech',
    instagram_account_url = 'https://instagram.com/brightfuturetech',
    youtube_channel_url = 'https://youtube.com/brightfuturetech',
    linkedin_profile_url = 'https://linkedin.com/company/brightfuturetech',
    google_my_business_url = 'https://g.page/brightfuturetech',
    
    -- Emergency Contacts
    emergency_contact_person = 'Dr. Anil Kumar',
    local_police_station_contact = '+91-100',
    nearest_hospital_contact = '+91-108',
    fire_department_contact = '+91-101',
    
    -- Documents - ALL JSONB
    business_registration_certificate = 'https://example.com/business-cert.pdf',
    education_board_affiliation_certificate = 'https://example.com/affiliation-cert.pdf',
    fire_safety_certificate = 'https://example.com/fire-safety-cert.pdf',
    building_plan_approval = 'https://example.com/building-approval.pdf',
    pan_card_document = 'https://example.com/pan-card.pdf',
    gst_certificate_document = 'https://example.com/gst-cert.pdf',
    bank_account_details_document = 'https://example.com/bank-details.pdf',
    institution_photographs = '["https://example.com/photo1.jpg", "https://example.com/photo2.jpg"]'::jsonb,
    insurance_documents = '["https://example.com/insurance1.pdf", "https://example.com/insurance2.pdf"]'::jsonb,
    accreditation_certificates = '["https://example.com/naac-cert.pdf", "https://example.com/nba-cert.pdf"]'::jsonb,
    award_certificates = '["https://example.com/award1.pdf", "https://example.com/award2.pdf"]'::jsonb,
    faculty_qualification_certificates = '["https://example.com/faculty1.pdf", "https://example.com/faculty2.pdf"]'::jsonb,
    safety_compliance_certificates = '["https://example.com/safety1.pdf", "https://example.com/safety2.pdf"]'::jsonb,
    
    -- Verification
    verified = true,
    updated_at = NOW()
WHERE user_id = '6b0f0c18-08fe-431b-af56-c4ab23e3b25c';

-- 3. Verify the update
SELECT 
    'Updated State' as check_type,
    id,
    institution_name,
    institution_type,
    established_year,
    registration_number,
    pan_number,
    gst_number,
    official_email,
    primary_contact_number,
    secondary_contact_number,
    website_url,
    address,
    city,
    state,
    pin_code,
    landmark,
    owner_name,
    owner_contact_number,
    course_categories,
    course_details,
    class_timings,
    total_classrooms,
    classroom_capacity,
    library_available,
    computer_lab_available,
    wifi_available,
    parking_available,
    cafeteria_available,
    total_current_students,
    average_batch_size,
    student_teacher_ratio,
    admission_fees,
    security_deposit,
    total_teaching_staff,
    total_non_teaching_staff,
    principal_director_name,
    principal_director_qualification,
    principal_director_experience,
    phd_holders,
    post_graduates,
    graduates,
    professional_certified,
    awards_received,
    publications,
    industry_experience,
    training_programs,
    board_exam_results,
    competitive_exam_results,
    institution_awards,
    student_achievements,
    accreditations,
    success_stories,
    courses,
    payment_modes,
    emi_available,
    payment_schedule,
    late_payment_penalty,
    scholarship_available,
    scholarship_criteria,
    discount_multiple_courses,
    sibling_discount,
    early_bird_discount,
    education_loan_assistance,
    installment_facility,
    hardship_support,
    primary_contact_person,
    contact_designation,
    contact_phone_number,
    contact_email_address,
    whatsapp_number,
    best_time_to_contact,
    facebook_page_url,
    instagram_account_url,
    youtube_channel_url,
    linkedin_profile_url,
    google_my_business_url,
    emergency_contact_person,
    local_police_station_contact,
    nearest_hospital_contact,
    fire_department_contact,
    business_registration_certificate,
    education_board_affiliation_certificate,
    fire_safety_certificate,
    building_plan_approval,
    pan_card_document,
    gst_certificate_document,
    bank_account_details_document,
    institution_photographs,
    insurance_documents,
    accreditation_certificates,
    award_certificates,
    faculty_qualification_certificates,
    safety_compliance_certificates,
    verified,
    created_at,
    updated_at
FROM institution_profiles 
WHERE user_id = '6b0f0c18-08fe-431b-af56-c4ab23e3b25c';
