// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kumlliwulkwljbrlremp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1bWxsaXd1bGt3bGpicmxyZW1wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAwNDQ3ODgsImV4cCI6MjA3NTYyMDc4OH0.HerwuPEbvk2gLKYQfvqvG1cRkjFe4IiBMk6QqLTw5gU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});